/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora.imc.View;

/**
 *
 * @author Pichau
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        botaoTelaPrincipalIMC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botaoTelaPrincipalIMC1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        OpcoesTelaPrincipal = new javax.swing.JMenu();
        calculadoraIMCmenu = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(472, 381));
        setResizable(false);

        botaoTelaPrincipalIMC.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botaoTelaPrincipalIMC.setText("TMB");
        botaoTelaPrincipalIMC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoTelaPrincipalIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTelaPrincipalIMCActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora");
        jLabel1.setAlignmentY(0.0F);

        botaoTelaPrincipalIMC1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botaoTelaPrincipalIMC1.setText("IMC");
        botaoTelaPrincipalIMC1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoTelaPrincipalIMC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTelaPrincipalIMC1ActionPerformed(evt);
            }
        });

        OpcoesTelaPrincipal.setText("Opções");
        OpcoesTelaPrincipal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        calculadoraIMCmenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        calculadoraIMCmenu.setText("Calculadora IMC");
        calculadoraIMCmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculadoraIMCmenuActionPerformed(evt);
            }
        });
        OpcoesTelaPrincipal.add(calculadoraIMCmenu);

        jMenuItem1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem1.setText("Calculadora TMB");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        OpcoesTelaPrincipal.add(jMenuItem1);

        jMenuBar1.add(OpcoesTelaPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoTelaPrincipalIMC1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoTelaPrincipalIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(botaoTelaPrincipalIMC, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(botaoTelaPrincipalIMC1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoTelaPrincipalIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTelaPrincipalIMCActionPerformed
        TelaCalculadoraTMB imc = new TelaCalculadoraTMB();
        imc.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_botaoTelaPrincipalIMCActionPerformed

    private void botaoTelaPrincipalIMC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTelaPrincipalIMC1ActionPerformed
        TelaCalculadoraIMC tela = new TelaCalculadoraIMC();
        tela.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_botaoTelaPrincipalIMC1ActionPerformed

    private void calculadoraIMCmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculadoraIMCmenuActionPerformed
        TelaCalculadoraIMC tela = new TelaCalculadoraIMC();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_calculadoraIMCmenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaCalculadoraTMB tela = new TelaCalculadoraTMB();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu OpcoesTelaPrincipal;
    private javax.swing.JButton botaoTelaPrincipalIMC;
    private javax.swing.JButton botaoTelaPrincipalIMC1;
    private javax.swing.JMenuItem calculadoraIMCmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
