/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora.imc.View;

import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class TelaCalculadoraIMC extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadoraIMC
     */
    public TelaCalculadoraIMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCalculadoraIMC = new javax.swing.JLabel();
        campoTextoPeso = new javax.swing.JTextField();
        campoTextoAltura = new javax.swing.JTextField();
        botaoCalcular = new javax.swing.JButton();
        labelAltura = new javax.swing.JLabel();
        labelPeso = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuOpcoes = new javax.swing.JMenu();
        menuCalculadoraTMB = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelCalculadoraIMC.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelCalculadoraIMC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCalculadoraIMC.setText("calculadora índice de massa corporal");

        campoTextoPeso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campoTextoPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoTextoAltura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campoTextoAltura.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        botaoCalcular.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        botaoCalcular.setText("calcular");
        botaoCalcular.setMaximumSize(new java.awt.Dimension(90, 26));
        botaoCalcular.setMinimumSize(new java.awt.Dimension(90, 26));
        botaoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalcularActionPerformed(evt);
            }
        });

        labelAltura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelAltura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAltura.setText("Altura(cm)");

        labelPeso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelPeso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPeso.setText("Peso(kg)");

        menuOpcoes.setText("Opções");
        menuOpcoes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        menuCalculadoraTMB.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menuCalculadoraTMB.setText("Calculador TMB");
        menuCalculadoraTMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCalculadoraTMBActionPerformed(evt);
            }
        });
        menuOpcoes.add(menuCalculadoraTMB);

        barraMenu.add(menuOpcoes);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelCalculadoraIMC, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(botaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoTextoAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(labelAltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoTextoPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCalculadoraIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAltura)
                    .addComponent(labelPeso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(botaoCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCalculadoraTMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCalculadoraTMBActionPerformed
        TelaCalculadoraTMB tela = new TelaCalculadoraTMB();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuCalculadoraTMBActionPerformed

    private void botaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalcularActionPerformed
        try{
            double imc;
            double altura = Double.parseDouble(campoTextoAltura.getText()) * 0.01;
            double peso = Double.parseDouble(campoTextoPeso.getText());
            
            if((altura > 0) && (peso > 0)){
                
                imc = peso / (altura * altura);
                
                if(imc < 18.5){
                    
                    JOptionPane.showMessageDialog(null, "Classificado como : Magreza");
                    
                }else if(imc >= 18.5 && imc < 25.0){
                    
                    JOptionPane.showMessageDialog(null, "Classificado como : Normal");
                    
                }else if(imc >= 25.0 && imc < 30.0){
                    
                    JOptionPane.showMessageDialog(null, "Classificado como : Sobrepeso");
                    
                }else if(imc >= 30.0 && imc < 40.0){
                    
                    JOptionPane.showMessageDialog(null, "Classificado como : Obesidade");
                    
                }else{
                    
                    JOptionPane.showMessageDialog(null, "Classificado como : Obesidade grave");
 
                }
                
            }else{
                
                JOptionPane.showMessageDialog(null, "Preencha todas as informações", "ERRO", JOptionPane.ERROR_MESSAGE);               
            }
  
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "Preencha todas as informações", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadoraIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadoraIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadoraIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadoraIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadoraIMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botaoCalcular;
    private javax.swing.JTextField campoTextoAltura;
    private javax.swing.JTextField campoTextoPeso;
    private javax.swing.JLabel labelAltura;
    private javax.swing.JLabel labelCalculadoraIMC;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JMenuItem menuCalculadoraTMB;
    private javax.swing.JMenu menuOpcoes;
    // End of variables declaration//GEN-END:variables
}
