/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora.imc.View;

import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class TelaCalculadoraTMB extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadoraIMC
     */
    public TelaCalculadoraTMB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCalculadora = new javax.swing.JLabel();
        boxNivelAtividades = new javax.swing.JComboBox<>();
        boxSexo = new javax.swing.JComboBox<>();
        campoTextoAltura = new javax.swing.JTextField();
        campoTextoPeso = new javax.swing.JTextField();
        campoTextoIdade = new javax.swing.JTextField();
        labelSexo = new javax.swing.JLabel();
        labelNivelAtividade = new javax.swing.JLabel();
        botaoCalcular = new javax.swing.JButton();
        labelAltura = new javax.swing.JLabel();
        labelPeso = new javax.swing.JLabel();
        labelIdade = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        opcaoCalculadoraIMCmenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelCalculadora.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelCalculadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCalculadora.setText("calculadora metabolismo basal");
        labelCalculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelCalculadora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        boxNivelAtividades.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boxNivelAtividades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Sedentário (pouco ou nenhum exercício)", "Levemente ativo (exercício leve - 1 a 3 dias por semana)", "Moderadamente ativo (exercício moderado - 3 a 5 dias por semana)", "Muito ativo (exercício pesado - 5 a 6 dias por semana)", "Extremamente ativo (exercício pesado diário ou até 2x por dia)" }));

        boxSexo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Masculino", "Feminino" }));

        campoTextoAltura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campoTextoAltura.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoTextoPeso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campoTextoPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoTextoPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoPesoActionPerformed(evt);
            }
        });

        campoTextoIdade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campoTextoIdade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoTextoIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoIdadeActionPerformed(evt);
            }
        });

        labelSexo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelSexo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSexo.setText("SEXO");

        labelNivelAtividade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelNivelAtividade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNivelAtividade.setText("NÍVEL DE ATIVIDADE");

        botaoCalcular.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        botaoCalcular.setText("calcular");
        botaoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalcularActionPerformed(evt);
            }
        });

        labelAltura.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        labelAltura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAltura.setText("ALTURA(cm)");

        labelPeso.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        labelPeso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPeso.setText("PESO(kg)");

        labelIdade.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        labelIdade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIdade.setText("IDADE");

        opcaoCalculadoraIMCmenu.setText("Opções");
        opcaoCalculadoraIMCmenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem1.setText("Calculadora IMC");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        opcaoCalculadoraIMCmenu.add(jMenuItem1);

        barraMenu.add(opcaoCalculadoraIMCmenu);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(campoTextoAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                        .addComponent(labelAltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoTextoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(160, 160, 160))
                                .addComponent(labelCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(boxSexo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boxNivelAtividades, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(campoTextoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(labelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(labelNivelAtividade))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(botaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNivelAtividade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxNivelAtividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(labelSexo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAltura)
                    .addComponent(labelPeso)
                    .addComponent(labelIdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoTextoPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoPesoActionPerformed

    private void campoTextoIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoIdadeActionPerformed

    private void botaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalcularActionPerformed
        try{
            double tmb;
            double peso = Double.parseDouble(campoTextoPeso.getText());
            double altura = Double.parseDouble(campoTextoAltura.getText());
            int idade = Integer.parseInt(campoTextoIdade.getText());
            String sexo = boxSexo.getSelectedItem().toString();
            int nvAtividade = boxNivelAtividades.getSelectedIndex();
        
            double nivelAtividade[] = {0, 1.2, 1.375, 1.55, 1.725, 1.9};
        
            if((!sexo.equals("-")) && (altura > 100) && (peso > 20) && (nvAtividade > 0)){
                
                if(sexo.equalsIgnoreCase("Feminino")){
                    
                    tmb = nivelAtividade[nvAtividade] * (655 + 9.6 * peso + 1.8 * altura - 4.7 * idade);
                    
                } else {
                    
                    tmb = nivelAtividade[nvAtividade] * (66 + 13.7 * peso + 5 * altura - 6.8 * idade);
                }
                JOptionPane.showMessageDialog(null, "O seu gasto calórico diário é de " + (int) tmb + "kcal");
    
            }else{
                JOptionPane.showMessageDialog(null, "Preencha todas as informações", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "Preencha todas as informações", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_botaoCalcularActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaCalculadoraIMC tela = new TelaCalculadoraIMC();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadoraTMB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadoraTMB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadoraTMB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadoraTMB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadoraTMB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botaoCalcular;
    private javax.swing.JComboBox<String> boxNivelAtividades;
    private javax.swing.JComboBox<String> boxSexo;
    private javax.swing.JTextField campoTextoAltura;
    private javax.swing.JTextField campoTextoIdade;
    private javax.swing.JTextField campoTextoPeso;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel labelAltura;
    private javax.swing.JLabel labelCalculadora;
    private javax.swing.JLabel labelIdade;
    private javax.swing.JLabel labelNivelAtividade;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JMenu opcaoCalculadoraIMCmenu;
    // End of variables declaration//GEN-END:variables
}
